name = "Terms"
uuid = "faceda62-1099-11e9-2df8-4d2b97a880ac"
authors = ["Harrison Grodin <harrison.grodin@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
